# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: mf_lastchanges
version: '0.9'
author: 'Daniel Springer, Medienfeuer'
compile: 0

page:
  title: 'Zuletzt geändert'
  perm: mf_lastchanges[]
  pjax: true
  icon: rex-icon fa fa-clock-o
  subpages:
    lastchanges: { title: 'translate:mf_lastchanges_lastchanges', perm: 'mf_lastchanges[lastchanges]', icon: rex-icon fa-file-text-o } # Letzte Artikel-Änderungen anzeigen
    lastchanges_media: { title: 'translate:mf_lastchanges_media', perm: 'mf_lastchanges[media]', icon: rex-icon fa-picture-o } # Letzte Medien-Änderungen anzeigen


requires:
    packages:
    
    redaxo: '>=5.0'
